blank_issues_enabled: true
contact_links:
  - name: Discussions
    url: https://github.com/DayuanJiang/next-ai-draw-io/discussions
    about: Have questions or ideas? Feel free to start a discussion
